---
- hosts: appserver
  become: yes
  tasks:
  - name: install openjdk 8
    apt:
       name: openjdk-8-jdk
       state: present
  - name: install tomcat 7
    apt:
       name: tomcat
       state: present
  - name: download jenkins to webapps/
    get_url:
       url: http://mirrors.jenkins.io/war/latest/jenkins.war
       dest: /usr/share/tomcat/webapps/jenkins.war
  - name: enable and start tomcat
    service:
      name: tomcat
      state: started
      enabled: yes
